services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app:/app

  php:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    volumes:
      - ./app:/app
    environment:
      DB_HOST: mysql
      DB_NAME: grand_transmission_auto
      DB_USER: developer
      DB_PASSWORD: secret123
      DB_CHARSET: utf8mb4

  mysql:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'secret123'
      MYSQL_USER: 'developer'
      MYSQL_PASSWORD: 'secret123'
      MYSQL_DATABASE: 'grand_transmission_auto'
    volumes:
      - mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql

volumes:
  mysqldata: {}
